#####
## Environment file defining the JASMIN Heat resources
#####

resource_registry:
  # Generic resources
  "JASMIN::Config::InstallHeatAgents": "config/heat_agents/install.yaml"
  "JASMIN::Base::Server": "base/server.yaml"
  # Generic configuration resources
  "JASMIN::Config::GitClone": "config/git_clone.yaml"
  # Kubernetes resources
  "JASMIN::Kubernetes::Kubeadm": "kubernetes/kubeadm.yaml"
  "JASMIN::Kubernetes::Server": "kubernetes/server.yaml"
  "JASMIN::Kubernetes::Master": "kubernetes/master.yaml"
  "JASMIN::Kubernetes::Worker": "kubernetes/worker.yaml"
