#####
## Environment file defining the JASMIN Heat resources
#####

parameters:
  # This is the ID of the current CentOS 7 image on JASMIN
  image: d2b7e3a8-3dbb-4cfc-a069-773e0e9a30a2
  # This is the current HEAD of the k8s-ansible playbook
  k8s_ansible_version: 03e83334e1a73c7d4e57a4b225bea0983a9a2168

resource_registry:
  # Generic resources
  "JASMIN::Base::InstallHeatAgents": "base/heat_agents/install.yaml"
  "JASMIN::Base::Server": "base/server.yaml"
  # Kubernetes resources
  "JASMIN::Kubernetes::Kubeadm": "kubernetes/config/kubeadm.yaml"
  "JASMIN::Kubernetes::OpenstackIntegration": "kubernetes/config/openstack_integration.yaml"
  "JASMIN::Kubernetes::Server": "kubernetes/server.yaml"
  "JASMIN::Kubernetes::Master": "kubernetes/master.yaml"
  "JASMIN::Kubernetes::Worker": "kubernetes/worker.yaml"
  "JASMIN::Kubernetes::Cluster": "kubernetes/cluster.yaml"
