#####
## Environment file defining the JASMIN Heat resources and common parameters
#####

parameters:
  # This is the ID of the current CentOS 7 image on JASMIN
  image: d2b7e3a8-3dbb-4cfc-a069-773e0e9a30a2

resource_registry:
  # Base resources
  "JASMIN::Base::InstallHeatAgents": "base/heat_agents/install.yaml"
  "JASMIN::Base::Server": "base/server.yaml"
  # Cluster-as-a-Service resources
  "JASMIN::CaaS::Manager": "caas/manager.yaml"
