#####
## Template for a software deployment resource with the correct signal type specified
#####

heat_template_version: 2016-04-08


parameters:
  server:
    type: string
    label: The server to apply the configuration to
    constraints:
      - custom_constraint: nova.server

  actions:
    type: comma_delimited_list
    label: The lifecycle actions that will trigger the deployment
    default:
      - CREATE
      - UPDATE

  config:
    type: string
    label: The configuration to apply

  input_values:
    type: json
    label: Input values for the software configuration
    default: {}


resources:
  deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: HEAT_SIGNAL
      server: { get_param: server }
      actions: { get_param: actions }
      config: { get_param: config }
      input_values: { get_param: input_values }


outputs:
  deployment:
    value: { get_resource: deployment }
