#####
## Template for a configuration that checks out a git repository
#####

heat_template_version: 2016-04-08


parameters:
  server:
    type: string
    label: The server to configure
    constraints:
      - custom_constraint: nova.server

  repository:
    type: string
    label: The repository to clone

  version:
    type: string
    label: The version to check out
    default: HEAD

  destination:
    type: string
    label: The destination path


resources:
  config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
        - name: repository
        - name: version
        - name: destination
      config: |
        ---
        - hosts: localhost
          connection: local
          tasks:
            - name: Install git
              yum:
                name: git
                state: latest
            - name: Ensure destination directory exists
              file:
                path: "{{ destination }}"
                state: directory
            - name: Clone repository
              git:
                repo: "{{ repository }}"
                version: "{{ version }}"
                dest: "{{ destination }}"

  deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: HEAT_SIGNAL
      config: { get_resource: config }
      server: { get_param: server }
      input_values:
        repository: { get_param: repository }
        version: { get_param: version }
        destination: { get_param: destination }


outputs:
  config:
    value: { get_resource: config }

  deployment:
    value: { get_resource: deployment }
