#####
## Template for a configuration that runs the kubeadm role
#####

heat_template_version: 2016-04-08


parameters:
  server:
    type: string
    label: The server to configure
    constraints:
      - custom_constraint: nova.server

  # This should be set automatically by using environment.yaml
  kubernetes_version:
    type: string
    label: The Kubernetes version to deploy

  role:
    type: string
    label: The role to configure the server as
    constraints:
      - allowed_values: [master, worker]

  master_ip:
    type: string
    label: The IP of the master node (only required for workers)
    default: ""

  kubeadm_token:
    type: string
    label: The kubeadm token used to join the cluster (only required for workers)
    default: ""


resources:
  config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
        - name: kubernetes_version
        - name: kube_role
        - name: kube_master_ip
        - name: kubeadm_token
      config: |
        ---
        - hosts: localhost
          connection: local
          roles:
            - kubeadm
          # For some reason, $HOME isn't set which means kubectl can't find the config file
          # So we set it manually
          environment:
            HOME: /root

  deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: HEAT_SIGNAL
      config: { get_resource: config }
      server: { get_param: server }
      input_values:
        kubernetes_version: { get_param: kubernetes_version }
        kube_role: { get_param: role }
        kube_master_ip: { get_param: master_ip }
        kubeadm_token: { get_param: kubeadm_token }


outputs:
  config:
    value: { get_resource: config }

  deployment:
    value: { get_resource: deployment }
